[package]
name = "scarp/scuffed-rounds-remake"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Net = "vorlias/net@^3.0"
t = "osyrisrblx/t@^3.0"
react-lua = "uglypoe/react-lua@17.0.1"
matter = "matter-ecs/matter@0.8.5"